const constants = {
  STORAGE_PROVIDER_SERVICE: 'STORAGE_PROVIDER_SERVICE',
  STORAGE_PROVIDER_S3: 'STORAGE_PROVIDER_S3',
  STORAGE_PROVIDER_MOCK: 'STORAGE_PROVIDER_MOCK',
};

export default constants;
